# Generated by Django 5.2.11 on 2026-02-09 07:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: 'id-card', 'car', 'graduation-cap')", max_length=50, null=True, verbose_name='Icône')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie de pièce',
                'verbose_name_plural': 'Catégories de pièces',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Format: '+22890123456' ou '90123456'", regex='^(\\+228)?[0-9]{8}$')], verbose_name='Numéro de téléphone')),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('admin', 'Administrateur'), ('police', 'Agent de Police')], default='citoyen', max_length=20, verbose_name='Rôle')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declaration', models.CharField(choices=[('PERTE', 'Perte'), ('TROUVAILLE', 'Trouvaille')], max_length=15, verbose_name='Type de déclaration')),
                ('numero_piece', models.CharField(db_index=True, help_text="Ex: Numéro CNI, Passeport, Plaque d'immatriculation", max_length=100, verbose_name='Numéro de la pièce')),
                ('nom_sur_piece', models.CharField(max_length=200, verbose_name='Nom figurant sur la pièce')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('RETROUVE', 'Retrouvé/Correspondance trouvée'), ('RESTITUE', 'Restitué au propriétaire'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('lieu_perte', models.CharField(blank=True, max_length=300, null=True, verbose_name='Lieu de la perte/trouvaille')),
                ('date_perte', models.DateField(blank=True, null=True, verbose_name='Date de la perte/trouvaille')),
                ('photo_piece', models.ImageField(blank=True, null=True, upload_to='pieces/%Y/%m/', verbose_name='Photo de la pièce')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('numero_recepisse', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de récépissé')),
                ('remarques_admin', models.TextField(blank=True, null=True, verbose_name="Remarques de l'administrateur")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='declarations.categoriepiece', verbose_name='Catégorie')),
                ('declaration_correspondante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondances', to='declarations.declaration', verbose_name='Déclaration correspondante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Déclarant')),
            ],
            options={
                'verbose_name': 'Déclaration',
                'verbose_name_plural': 'Déclarations',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('MATCH', 'Correspondance trouvée'), ('STATUT', 'Changement de statut'), ('ADMIN', 'Message administrateur')], max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='declarations.declaration', verbose_name='Déclaration concernée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['numero_piece', 'type_declaration'], name='declaration_numero__59da5d_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['statut', 'date_declaration'], name='declaration_statut_f65813_idx'),
        ),
    ]
