# Generated by Django 5.2.11 on 2026-02-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='nom_declarant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de famille (sur la pièce)'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='prenom_declarant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom(s) (sur la pièce)'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
    ]
